# Generated by Django 6.0.4 on 2026-04-18 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Saque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chave_pix', models.CharField(max_length=100, verbose_name='Sua Chave Pix')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
