# Generated by Django 6.0.4 on 2026-10-02 01:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                (
                    "texto",
                    models.CharField(
                        blank=True,
                        help_text="Opcional: a frase/lance específico (quando a categoria é de pérolas, micos etc.).",
                        max_length=300,
                    ),
                ),
                (
                    "votos_ano_anterior",
                    models.PositiveIntegerField(
                        default=0, help_text="Votos na última edição."
                    ),
                ),
                (
                    "votos_anos_anteriores",
                    models.PositiveIntegerField(
                        default=0, help_text="Votos em edições mais antigas."
                    ),
                ),
            ],
            options={
                "ordering": ["-votos_ano_anterior", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Edicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField(unique=True)),
                ("titulo", models.CharField(default="Melhores do Ano", max_length=120)),
                (
                    "ativa",
                    models.BooleanField(
                        default=True,
                        help_text="Só a edição ativa aparece para os jogadores.",
                    ),
                ),
                (
                    "apostas_ate",
                    models.DateTimeField(
                        blank=True,
                        help_text="Prazo geral das apostas. Vazio = apostas abertas até a staff fechar cada categoria.",
                        null=True,
                    ),
                ),
                (
                    "margem_casa",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.12"),
                        help_text="Margem aplicada às odds (0.12 = 12%). Quanto maior, menores as odds.",
                        max_digits=3,
                    ),
                ),
                (
                    "coins_por_voto",
                    models.PositiveIntegerField(
                        default=200,
                        help_text="A cada X coins apostados em um candidato, ele ganha 1 'voto' virtual e a odd cai. Menor = odds mais sensíveis ao movimento da galera.",
                    ),
                ),
                (
                    "peso_anos_anteriores",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.25"),
                        help_text="Peso de cada voto de anos antes do último (o último ano vale 1.00).",
                        max_digits=3,
                    ),
                ),
            ],
            options={
                "verbose_name": "Edição",
                "verbose_name_plural": "Edições",
                "ordering": ["-ano"],
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60)),
                ("nome", models.CharField(max_length=120)),
                ("emoji", models.CharField(default="🏆", max_length=8)),
                ("descricao", models.CharField(blank=True, max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pessoa", "Pessoa"),
                            ("autor", "Autor da frase/lance"),
                            ("nome", "Nome do grupo"),
                        ],
                        default="pessoa",
                        max_length=10,
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "aberta",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para travar as apostas desta categoria.",
                    ),
                ),
                ("liquidada", models.BooleanField(default=False)),
                (
                    "vencedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="melhores.candidato",
                    ),
                ),
                (
                    "edicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias",
                        to="melhores.edicao",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem", "id"],
                "unique_together": {("edicao", "slug")},
            },
        ),
        migrations.AddField(
            model_name="candidato",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidatos",
                to="melhores.categoria",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="candidato",
            unique_together={("categoria", "nome", "texto")},
        ),
        migrations.CreateModel(
            name="Aposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.PositiveIntegerField()),
                ("odd_travada", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("ganha", "Ganha"),
                            ("perdida", "Perdida"),
                            ("anulada", "Anulada"),
                        ],
                        default="aberta",
                        max_length=10,
                    ),
                ),
                ("retorno", models.PositiveIntegerField(default=0)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apostas_melhores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apostas",
                        to="melhores.candidato",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apostas",
                        to="melhores.categoria",
                    ),
                ),
            ],
            options={
                "ordering": ["-atualizada_em"],
                "unique_together": {("usuario", "categoria")},
            },
        ),
    ]
