# Generated by Django 6.0.4 on 2026-10-02 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("melhores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Multipla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.PositiveIntegerField()),
                ("odd_total", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("ganha", "Ganha"),
                            ("perdida", "Perdida"),
                            ("anulada", "Anulada"),
                        ],
                        default="aberta",
                        max_length=10,
                    ),
                ),
                ("retorno", models.PositiveIntegerField(default=0)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "edicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiplas",
                        to="melhores.edicao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiplas_melhores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-criada_em"],
            },
        ),
        migrations.CreateModel(
            name="MultiplaSelecao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odd_travada", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("ganha", "Ganha"),
                            ("perdida", "Perdida"),
                            ("anulada", "Anulada"),
                        ],
                        default="aberta",
                        max_length=10,
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selecoes_multipla",
                        to="melhores.candidato",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selecoes_multipla",
                        to="melhores.categoria",
                    ),
                ),
                (
                    "multipla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selecoes",
                        to="melhores.multipla",
                    ),
                ),
            ],
            options={
                "unique_together": {("multipla", "categoria")},
            },
        ),
    ]
