# Generated by Django 6.0.4 on 2026-04-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocacao', '0002_jogador_modalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='jogadores/'),
        ),
    ]
