# Generated by Django 6.0.4 on 2026-04-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocacao', '0003_jogador_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='convocado_oficial',
            field=models.BooleanField(default=False, help_text='Marque esta opção quando o técnico oficializar a convocação na vida real.'),
        ),
    ]
