# Generated by Django 6.0.4 on 2026-04-17 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('resenha', 'Modo Resenha (Livre)'), ('pago', 'Modo Pago (Premiado)')], default='resenha', max_length=10)),
                ('aprovado', models.BooleanField(default=False)),
                ('data_adesao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participacao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
