# Generated by Django 6.0.4 on 2026-04-17 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_casa', models.CharField(max_length=100)),
                ('time_fora', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField()),
                ('gols_casa_real', models.IntegerField(blank=True, null=True)),
                ('gols_fora_real', models.IntegerField(blank=True, null=True)),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Palpite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_casa', models.IntegerField()),
                ('gols_fora', models.IntegerField()),
                ('pontuacao_obtida', models.IntegerField(default=0)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpites', to='palpites.jogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'jogo')},
            },
        ),
    ]
