# Generated by Django 6.0.4 on 2026-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palpite',
            name='modalidade',
            field=models.CharField(choices=[('resenha', 'Resenha'), ('pago', 'Pago')], default='resenha', max_length=10),
        ),
    ]
