# Generated by Django 6.0.4 on 2026-04-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0002_palpite_modalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='escudo_casa',
            field=models.ImageField(blank=True, null=True, upload_to='escudos/'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='escudo_fora',
            field=models.ImageField(blank=True, null=True, upload_to='escudos/'),
        ),
    ]
