# Generated by Django 6.0.4 on 2026-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0003_jogo_escudo_casa_jogo_escudo_fora'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='premio_distribuido',
            field=models.BooleanField(default=False),
        ),
    ]
