# Generated by Django 6.0.4 on 2026-04-24 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('elenco', 'Elenco Histórico (Ex: Itália 2006)'), ('trajetoria', 'Trajetória de Clubes')], max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('resposta_oculta', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='duelos/itens/')),
                ('posicao_tatica', models.CharField(blank=True, max_length=50)),
                ('ordem', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='duelos.categoriadesafio')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='PartidaDuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno_iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('pontos_criador', models.IntegerField(default=0)),
                ('pontos_convidado', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Oponente'), ('andamento', 'Em Andamento'), ('finalizado', 'Finalizado')], default='aguardando', max_length=20)),
                ('erros_acumulados', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duelos.categoriadesafio')),
                ('itens_revelados', models.ManyToManyField(blank=True, to='duelos.itemdesafio')),
                ('jogador_convidado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duelos_aceitos', to=settings.AUTH_USER_MODEL)),
                ('jogador_criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duelos_criados', to=settings.AUTH_USER_MODEL)),
                ('turno_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meu_turno_duelo', to=settings.AUTH_USER_MODEL)),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duelos_vencidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
