# Generated by Django 6.0.4 on 2026-04-29 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('escudo', models.ImageField(upload_to='duelos/clubes/')),
            ],
        ),
        migrations.CreateModel(
            name='JogadorBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='categoriadesafio',
            name='tipo',
            field=models.CharField(choices=[('elenco', 'Elencos clássicos'), ('trajetoria', 'Jogo da trajetória')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itemdesafio',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemdesafio',
            name='clube_vinculado',
            field=models.ForeignKey(blank=True, help_text='Selecione do banco de escudos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='duelos.clube'),
        ),
        migrations.AddField(
            model_name='itemdesafio',
            name='jogador_vinculado',
            field=models.ForeignKey(blank=True, help_text='Selecione do banco de jogadores', null=True, on_delete=django.db.models.deletion.SET_NULL, to='duelos.jogadorbanco'),
        ),
    ]
