# Generated by Django 6.0.4 on 2026-05-01 21:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duelos', '0002_clube_jogadorbanco_alter_categoriadesafio_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubeFutebol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_limite_inscricao', models.DateTimeField(help_text='Data e hora que as inscrições se encerram.')),
                ('status', models.CharField(choices=[('inscricoes', 'Inscrições Abertas'), ('andamento', 'Em Andamento'), ('finalizado', 'Finalizado')], default='inscricoes', max_length=20)),
                ('codigo_convite', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campeonatos_criados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfrontoCampeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('oitavas', 'Oitavas de Final'), ('quartas', 'Quartas de Final'), ('semi', 'Semifinal'), ('final', 'Grande Final')], max_length=20)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Adversário/Jogadores'), ('andamento', 'Bola Rolando'), ('finalizado', 'Finalizado'), ('wo', 'Vencedor por W.O.')], default='aguardando', max_length=20)),
                ('ordem_chave', models.IntegerField(default=0, help_text='Para organizar o desenho do chaveamento no front-end')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confrontos', to='duelos.campeonato')),
                ('desafio_sorteado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='duelos.categoriadesafio')),
                ('jogador1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confrontos_como_j1', to=settings.AUTH_USER_MODEL)),
                ('jogador2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confrontos_como_j2', to=settings.AUTH_USER_MODEL)),
                ('partida_vinculada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='duelos.partidaduelo')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confrontos_vencidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartidaMiniFanaticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='aguardando', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('clube_dupla_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_a', to='duelos.clubefutebol')),
                ('clube_dupla_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_b', to='duelos.clubefutebol')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_criadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('multipla', 'Múltipla Escolha'), ('aberta', 'Resposta Aberta (Texto)')], default='multipla', max_length=20)),
                ('texto_pergunta', models.TextField(help_text='Ex: Qual jogador foi artilheiro em 2013?')),
                ('opcao_a', models.CharField(blank=True, max_length=255, null=True)),
                ('opcao_b', models.CharField(blank=True, max_length=255, null=True)),
                ('opcao_c', models.CharField(blank=True, max_length=255, null=True)),
                ('opcao_d', models.CharField(blank=True, max_length=255, null=True)),
                ('resposta_correta', models.CharField(max_length=255)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='duelos.clubefutebol')),
            ],
        ),
        migrations.CreateModel(
            name='InscricaoCampeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='duelos.campeonato')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('campeonato', 'jogador')},
            },
        ),
        migrations.CreateModel(
            name='JogadorMiniFanaticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dupla', models.CharField(choices=[('A', 'Dupla A'), ('B', 'Dupla B')], max_length=1)),
                ('pontos', models.IntegerField(default=0)),
                ('tempo_gasto_segundos', models.FloatField(default=0.0)),
                ('finalizou', models.BooleanField(default=False)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='duelos.partidaminifanaticos')),
            ],
            options={
                'unique_together': {('partida', 'jogador')},
            },
        ),
    ]
