# Generated by Django 6.0.4 on 2026-05-03 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duelos', '0003_clubefutebol_campeonato_confrontocampeonato_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaTrunfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('posicao', models.CharField(help_text='Ex: ATA, MEI, ZAG, GOL', max_length=5)),
                ('overall', models.IntegerField(default=50, help_text='Nota geral da carta')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cartas/')),
                ('ritmo', models.IntegerField(default=50)),
                ('finalizacao', models.IntegerField(default=50)),
                ('passe', models.IntegerField(default=50)),
                ('drible', models.IntegerField(default=50)),
                ('defesa', models.IntegerField(default=50)),
                ('fisico', models.IntegerField(default=50)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duelos.clubefutebol')),
            ],
        ),
        migrations.CreateModel(
            name='PartidaTrunfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='aguardando', max_length=20)),
                ('pontos_criador', models.IntegerField(default=0)),
                ('pontos_convidado', models.IntegerField(default=0)),
                ('rodada_atual', models.IntegerField(default=1)),
                ('carta_convidado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='duelos.cartatrunfo')),
                ('carta_criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='duelos.cartatrunfo')),
                ('convidado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trunfos_convidados', to=settings.AUTH_USER_MODEL)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trunfos_criados', to=settings.AUTH_USER_MODEL)),
                ('turno_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trunfos_turnos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
