# Generated by Django 6.0.4 on 2026-05-04 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duelos', '0004_cartatrunfo_partidatrunfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandeFinalCampeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar_j1', models.IntegerField(default=0)),
                ('placar_j2', models.IntegerField(default=0)),
                ('tempo_total_j1', models.FloatField(default=0.0)),
                ('tempo_total_j2', models.FloatField(default=0.0)),
                ('fase_atual', models.CharField(choices=[('aguardando', 'Aguardando Finalistas'), ('trajetoria', 'Round 1: Carreira Misteriosa'), ('escalacao', 'Round 2: Prancheta do Professor'), ('trunfo', 'Round 3: Super Trunfo'), ('minifanaticos', 'Round 4: Quiz 1v1'), ('finalizado', 'Pódio e Premiação')], default='aguardando', max_length=20)),
                ('id_partida_trajetoria', models.IntegerField(blank=True, null=True)),
                ('id_partida_escalacao', models.IntegerField(blank=True, null=True)),
                ('id_partida_trunfo', models.IntegerField(blank=True, null=True)),
                ('id_partida_minifanaticos', models.IntegerField(blank=True, null=True)),
                ('campeonato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grande_final', to='duelos.campeonato')),
                ('jogador_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finais_disputadas_j1', to=settings.AUTH_USER_MODEL)),
                ('jogador_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finais_disputadas_j2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
